//Try Catch

const numero1 = 20;
const numero3 = 30;

console.log(numero1);


try {
    console.log(numero2);
    console.log(numero3);
} catch (error) {
    console.log(error);
}
